# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deepthinking',
                'doc_host': 'https://mckjzhangxk.github.io',
                'git_url': 'https://github.com/mckjzhangxk/deepthinking',
                'lib_path': 'deepthinking'},
  'syms': {'deepthinking.core': {'deepthinking.core.foo': ('core.html#foo', 'deepthinking/core.py')}}}
