# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_transformer.ipynb.

# %% auto 0
__all__ = ['batch_dataset']

# %% ../nbs/00_transformer.ipynb 2
# ! pip install datasets evaluate transformers[sentencepiece]
from transformers import AutoTokenizer
from transformers import AutoModel
from transformers import AutoModelForSequenceClassification
from transformers import AutoModelForCausalLM
from torch.utils.data import dataset, sampler, dataloader
from datasets import load_dataset,DatasetDict,Dataset
from transformers import BertConfig, BertModel,AutoConfig
from transformers import DataCollatorWithPadding
import pandas as pd
from transformers import Trainer,TrainingArguments,DataCollatorWithPadding
import numpy as np

# %% ../nbs/00_transformer.ipynb 50
def batch_dataset(ds, #数据集
                  mapping_func #func(example,maxlen)签名的函数
                 ):
    """
    使用`mapping_func`作用于数据集ds上，把转换后的结果返回
    """
    ds=ds.map(padd_func,batched=True)
    ds=ds.remove_columns(['sentence1','sentence2','idx']).rename_column('label','labels')
      # dataset.map返回的数据集，sample是存放在list中的，加上这句话，把list转换成对应的tensor
    ds=ds.with_format('torch')
    return ds
